#include <iostream>
#include <string>
#include <filesystem>

#include <opencv2/opencv.hpp>
#include "cam_lidar_calib/types.hpp"
#include <yaml-cpp/yaml.h>
#include "cam_lidar_calib/camera_detector.hpp"



int main()
{
	// Load project config
	cam_lidar_calib::CalibrationConfig  cfg = cam_lidar_calib::CalibrationConfig::fromYaml("../config/params.yaml");

	std::filesystem::path project_root = std::filesystem::current_path().parent_path();

	// Load camera intrinsics (generated by compute_intrinsics)
	std::filesystem::path intrinsics_path = project_root / cfg.cameraIntrinsicsPath;
	cam_lidar_calib::CameraIntrinsics intrinsics = cam_lidar_calib::CameraIntrinsics::fromYaml(intrinsics_path.string());

	std::cout << "Intrinsics loaded: fx=" << intrinsics.K(0,0) 
              << " fy=" << intrinsics.K(1,1)
              << " cx=" << intrinsics.K(0,2) 
              << " cy=" << intrinsics.K(1,2) << std::endl;

	// Create the detectors
	cam_lidar_calib::CameraDetector detector(cfg, intrinsics);
	cam_lidar_calib::LidarDetector lidar_detector(cfg);

	// Collect all image files
	std::filesystem::path image_path = project_root / cfg.imagesDir;
	std::vector<std::filesystem::path> image_files;

	// Collect all pointcloud files
	std::filesystem::path point_cloud_path = project_root / cfg.pointcloudsDir;
	std::vector<std::filesystem::path> point_cloud_files;

	for(const auto& entry : std::filesystem::directory_iterator(image_path)) {

		std::string ext = entry.path().extension().string();
		if (ext == ".jpg" || ext == ".jpeg" || ext == ".png" || ext == ".bmp")
			image_files.push_back(entry.path());
	}

	for (const auto& entry : std::filesystem::directory_iterator(point_cloud_path)) {

		std::string ext = entry.path().extension().string();
		if (ext == ".pcd")
			point_cloud_files.push_back(entry.path());
	}

	std::sort(image_files.begin(), image_files.end());
	std::sort(point_cloud_files.begin(), point_cloud_files.end());

	std::cout << "Found " << image_files.size() << "images in " << image_path << std::endl;
	std::cout << "Found " << point_cloud_files.size() << "point clouds in " << point_cloud_path << std::endl;

	// Prepare output directory for visualizations
	std::filesystem::path output_dir = project_root / std::filesystem::path(cfg.output).parent_path();
	std::filesystem::create_directories(output_dir);

	// Store successful detections for later use with optimizer
	std::vector<cam_lidar_calib::PlaneObservation> camera_observations;
	std::vector<cam_lidar_calib::PlaneObservation> lidar_observations;

	// Process each image
	for (size_t i = 0; i < image_files.size(); ++i)
	{
		cv::Mat image = cv::imread(image_files[i].string());
		if (image.empty()) {
			std::cerr << "SKIP, Cannot read: " << image_files[i].filename() << std::endl;
			continue;
		}

		// Run detection
		auto result = detector.detect(image, static_cast<int>(i));

		if (result.has_value()) {
			std::cout << "OK Frame: " << i << "(" << image_files[i].filename() << std::endl;
			std::cout << " Normal: [" << result->normal.x() << ", "
						<< result->normal.y() << ", "
						<< result->normal.z() << "]" << std::endl;
			std::cout << " Distance: " << result->distance << " m" << std::endl;
			std::cout << " Board points in camera frame: " << result->points.size() << std::endl;

			camera_observations.push_back(result.value());

			// Save visualization for this frame
			if (cfg.visual) {
				cv::Mat gray;
				cv::cvtColor(image, gray, cv::COLOR_BGR2GRAY);
				std::vector<cv::Point2f> corners;
				cv::findChessboardCorners(gray, cv::Size(cfg.cols, cfg.rows), corners,
					cv::CALIB_CB_ADAPTIVE_THRESH | cv::CALIB_CB_NORMALIZE_IMAGE | cv::CALIB_CB_FAST_CHECK);

				cv::Mat vis = detector.drawDetection(image, corners);
				std::string vis_name = "detected_frame_" + std::to_string(i) + ".png";
				cv::imwrite((output_dir / vis_name).string(), vis);
			
			}
		} else {
			std::cerr << " FAIL Frame " << i << "( " << image_files[i].filename() << ") - no board found" << std::endl;
		}
	}

	// Process each point cloud file
	for (size_t i = 0; i < point_cloud_files.size(); ++i)
	{
		auto result = lidar_detector.detectFromFile(point_cloud_files[i].string(), static_cast<int>(i));
		if (result.has_value()) {
			std::cout << "OK plane: " << i << "(" << point_cloud_files[i].filename() << std::endl;
			std::cout << "Normal. [" << result->normal.x() << ", "
									<< result->normal.y() << ", "
									<< result->normal.z() << "]" << std::endl;
			std::cout << "Distance: " << result->distance << "m" << std::endl;
			std::cout << "Board points in Lidar frame: " << result->points.size() << std::endl;


			lidar_observations.push_back(result.value());

			// Save visualizations for this frame
			if (cfg.visual) {

			}

		} else {
			std::cerr << "FAIL Plane " << i << "( " << point_cloud_files[i].filename() << ") - no board found" << std::endl;
		}
	}

	// Camera Calibration Summary
	std::cout << "CAMERA DETECTION SUMMARY" << std::endl;
	std::cout << "Images processed: " << image_files.size() << std::endl;
	std::cout << "Boards detected: " << camera_observations.size() << std::endl;

	if (!camera_observations.empty()) {
		std::cout << "/n Detected plane observations: " << std::endl;
		for (const auto& obs : camera_observations) {
			std::cout << "Frame " << obs.frame_index
						<<  "| Normal: [" << obs.normal.x() << ", " << obs.normal.y()
						<<  "| Distance: " << obs.distance << " m" << std::endl;
		}
	}

	// Lidar Calibration Summary
	std::cout << "LIDAR DETECTION SUMMARY " << std::endl;
	std::cout << "Points processed: " << point_cloud_files.size() << std::endl;
	std::cout << "Boards detected: " << lidar_observations.size() << std::endl;

	if (!lidar_observations.empty()) {
		std::cout << "/n Detected plane observations: " << std::endl;
		for (const auto& obs: lidar_observations) {
			std::cout << "Plane " << obs.frame_index
						<< "| Normal: [" << obs.normal.x() << ", " << obs.normal.y()
						<< "| Distance: " << obs.distance << " m" << std::endl;
		}
	}
	
	return 0;
}
